# Generated by Django 3.2 on 2022-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='yt_link',
            field=models.TextField(blank=True),
        ),
    ]
