# Generated by Django 3.2 on 2022-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='excerpt',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
